### ISSUE TITLE
EndsAt json field name is in different case

### ISSUE THREAD

**Issue by totemcaf** [gmauleon/alertmanager-zabbix-webhook#2]
`webhook/webhook.go` file has a field in Alert struct as:
```
EndsAt       string            `json:"EndsAt,omitempty"`
```

The sample field name in https://prometheus.io/docs/alerting/configuration/#%3Cwebhook_config%3E is:
```
"endsAt": "<rfc3339>",
```
There is a difference in first letter case.

**Comment by gmauleon** [comment]
Thanks @totemcaf
